version: '3'
services:
  app:
    image: erichough/nfs-server
    volumes:
      - /tmp/share:/etc/share
      - /tmp/exports.txt:/etc/exports:ro
    ports:
      - "2049:2049/tcp"
#      - "111:111/udp"
#      - "32765:32765/udp"
#      - "32767:32767/udp"
    cap_add:
      - SYS_ADMIN

