apiVersion: v1
kind: Service
metadata:
  name: timeis-service
spec:
  selector:
    app: timeis
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
    nodePort: 30002
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeis
spec:
  selector:
    matchLabels:
      app: timeis
  replicas: 3
  template:
    metadata:
      labels:
        app: timeis
    spec:
      containers:
      - name: timeis
        image: timeis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeis-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: timeis-service
            port:
              number: 80
